baseURL = "https://mmaxence.me"
languageCode = "en-us"
pluralizelisttitles = false
theme = "gohugo-theme-ananke"
title = "PO, Lead product Design at buzzvil"
Author = "Maxence Mauduit"
googleAnalytics= "UA-149702774-1"
enableRobotsTXT = "true"

[params]
  custom_css = ["dist/css/style.css"]
  custom_js = ["dist/js/script.js"]
  author = "Maxence Mauduit"
  description = "PO, Lead product Design at buzzvil"
  twitter = "https://twitter.com/mmaxence"
  linkedin = "https://www.linkedin.com/in/mmaxence/"
  github = "https://github.com/mmaxence"
  medium = "https://medium.com/@mmaxence.me"
  show_reading_time = true
  favicon = "images/favicon.png"
  
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
  
[menu]
  [[menu.main]]
    name = "Experience"
    title = "My experiences"
    url = "/experience/"
    weight = -140
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "blog section"
    url = "/blog/"
    weight = -130
  [[menu.main]]
    identifier = "read"
    name = "Bookshelf"
    title = "read"
    url = "/library/"
    slug = "read"
    weight = -110