baseURL = "https://mmaxence.me"
languageCode = "en-us"
pluralizelisttitles = false
theme = "gohugo-theme-ananke"
title = "Maxence Mauduit"
googleAnalytics= "UA-149702774-1"

[params]
  custom_css = ["dist/css/style.css"]
  custom_js = ["dist/js/script.js"]
  author = "Maxence Mauduit"
  description = "Designer at buzzvil"
  twitter = "https://twitter.com/mmaxence"
  linkedin = "https://www.linkedin.com/in/mmaxence/"
  github = "https://github.com/mmaxence"
  medium = "https://medium.com/@max_1206"
  show_reading_time = true
  favicon = "images/favicon.png"
  enableRobotsTXT = "true"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "write"
    title = "blog section"
    url = "/blog/"
    weight = -130
  [[menu.main]]
    identifier = "do"
    name = "do"
    title = "do"
    url = "/Projects/"
    slug="do"
    weight = -120
  [[menu.main]]
    identifier = "read"
    name = "read"
    title = "read"
    url = "/Library/"
    slug = "read"
    weight = -110