baseURL = "https://maxence-d5f05.firebaseapp.com"
languageCode = "en-us"
pluralizelisttitles = false
theme = "gohugo-theme-ananke"
title = "Maxence Mauduit"

[params]
  custom_css = ["dist/css/style.css"]
  custom_js = ["dist/js/script.js"]
  author = "Maxence Mauduit"
  description = "Designer at buzzvil"
  twitter = "https://twitter.com/mmaxence"
  linkedin = "https://www.linkedin.com/in/mmaxence/"
  github = "https://github.com/mmaxence"
  medium = "https://medium.com/@max_1206"
  show_reading_time = true
  favicon = "images/favicon.png"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "blog section"
    url = "/blog/"
    weight = -130
  [[menu.main]]
    identifier = "Projects"
    name = "Projects"
    title = "Projects section"
    url = "/Projects/"
    weight = -120
  [[menu.main]]
    identifier = "Shelf"
    name = "Shelf"
    title = "Bookshelf"
    url = "/Library/"
    weight = -110