baseURL = "http://example.org/"
languageCode = "en-us"
title = "Designer at buzzvil"
theme = "ananke"
custom_css = ["css/styles.css"]
pluralizelisttitles = false
sectionPagesMenu = "main"
[params]
  custom_css = ["dist/css/style.css"]
  author = "Maxence Mauduit"
  description = "Connecting Dots."
  twitter = "https://twitter.com/mmaxence"
  linkedin = "https://www.linkedin.com/in/mmaxence/"
  github = "https://github.com/mmaxence"
  medium = "https://medium.com/@max_1206"
  show_reading_time = true
  favicon = "images/favicon.png"
