baseURL = "https://maxence-d5f05.firebaseapp.com"
languageCode = "en-us"
custom_css = ["css/styles.css"]
pluralizelisttitles = false
sectionPagesMenu = "main"
theme = "gohugo-theme-ananke"
copyright = "Everything is mine"

[languages]
  [languages.en]
    LanguageName = "En"
    languageFlag = "🇬🇧"
    title = "Designer at buzzvil"
    weight = 1
    [languages.en.params]
      linkedin = "https://linkedin.com/whoever"
  [languages.fr]
    LanguageName = "Fr"
    languageFlag = "🇫🇷"
    title = "Designer chez buzzvil"
    weight = 2
    [languages.fr.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.fr.params.navigation]
        help = "Aide"
  [languages.ko]
  LanguageName = "Kr"
  languageFlag = "🇰🇷"
  title = "Designer chez buzzvil"
  weight = 2
  [languages.ko.params]
    linkedin = "https://linkedin.com/fr/whoever"
    [languages.ko.params.navigation]
      help = "Aide"

[params]
  custom_css = ["dist/css/style.css"]
  author = "Maxence Mauduit"
  description = "Connecting Dots."
  twitter = "https://twitter.com/mmaxence"
  linkedin = "https://www.linkedin.com/in/mmaxence/"
  github = "https://github.com/mmaxence"
  medium = "https://medium.com/@max_1206"
  show_reading_time = true
  favicon = "images/favicon.png"
  [params.navigation]
    help = "Help"
